### ISSUE TITLE
`cargo test` dies with unhandled `SIGUSR1`

### ISSUE THREAD

**Issue by jtracey** [nix-rust/nix#1661]
When I try to run `cargo test` on master, it usually dies with an unhanded `SIGUSR1`. Digging around a bit, I found that this only occurs if either [`test_sigwait()`](https://github.com/nix-rust/nix/blob/5cd01a1fd7417ee6e16636443965c0a197ff2843/src/sys/signal.rs#L1278) or [`test_signalfd()`](https://github.com/nix-rust/nix/blob/09bddc36769b4be38b6ce567c3352e2934204771/test/sys/test_signalfd.rs) are enabled (these are also the only tests that actually raise a signal, AFAICT). I can provide stack traces if you'd like, but the gist is that it's terminating in whatever random test, not the above tests. Each of the two tests have about a 90% chance of triggering the crash, `-j 1` doesn't seem to affect this probability. This is a clean checkout and test, no idea if it's a regression.

Running 432fb906150599c0072420f9524ac42080e1ca20 on Ubuntu 21.10 (Linux 5.13.0), rustc 1.58.1, cargo 1.58.0.

**Comment by asomers** [comment]
With `-j 1`, does it still crash in some random test, or only the tests that raise that signal? A stack trace might be helpful.  Or, `strace` output.

**Comment by jtracey** [comment]
When I run with a single thread in gdb or strace, it takes many more tries to trigger the error (I double checked, and a single thread outside still sees it most of the time).

<details><summary>gdb output</summary>

```gdb
(gdb) run --test-threads 1
Starting program: /home/jtracey/Documents/nix/target/debug/deps/nix-09e2df43abb053c6 --test-threads 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

running 48 tests
test features::os::test_parsing_kernel_version ... ok
test ifaddrs::tests::test_getifaddrs ... ok
test sys::aio::t::liocb_is_unpin ... ok
test sys::select::tests::fdset_clear ... ok
test sys::select::tests::fdset_fds ... ok
test sys::select::tests::fdset_highest ... ok
test sys::select::tests::fdset_insert ... ok
test sys::select::tests::fdset_remove ... ok
test sys::select::tests::test_select ... ok
test sys::select::tests::test_select_nfds ... ok
test sys::select::tests::test_select_nfds2 ... ok
test sys::signal::tests::test_clear ... ok
test sys::signal::tests::test_contains ... ok
test sys::signal::tests::test_extend ... ok
test sys::signal::tests::test_from_str_invalid_value ... ok
test sys::signal::tests::test_from_str_round_trips ... ok
test sys::signal::tests::test_sigaction ... [New Thread 0x7ffff7c79640 (LWP 2428448)]
ok
[Thread 0x7ffff7c79640 (LWP 2428448) exited]
test sys::signal::tests::test_sigwait ... [New Thread 0x7ffff7c79640 (LWP 2428449)]

Thread 1 "nix-09e2df43abb" received signal SIGUSR1, User defined signal 1.
__pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:806
806	pthread_create.c: No such file or directory.
(gdb) bt
#0  __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:806
#1  0x00005555555fa265 in std::sys::unix::thread::Thread::new () at library/std/src/sys/unix/thread.rs:85
#2  0x000055555559420d in std::thread::Builder::spawn_unchecked<nix::sys::signal::tests::test_sigwait::{closure#0}, ()> (self=..., f=...)
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/mod.rs:508
#3  0x00005555555961cc in std::thread::Builder::spawn<nix::sys::signal::tests::test_sigwait::{closure#0}, ()> (self=..., f=...)
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/mod.rs:389
#4  0x0000555555591c9f in std::thread::spawn<nix::sys::signal::tests::test_sigwait::{closure#0}, ()> (f=...)
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/thread/mod.rs:631
#5  0x000055555557c40e in nix::sys::signal::tests::test_sigwait () at src/sys/signal.rs:1236
#6  0x00005555555719aa in nix::sys::signal::tests::test_sigwait::{closure#0} () at src/sys/signal.rs:1235
#7  0x0000555555575c2e in core::ops::function::FnOnce::call_once<nix::sys::signal::tests::test_sigwait::{closure#0}, ()> ()
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227
#8  0x00005555555cf5f3 in core::ops::function::FnOnce::call_once<fn(), ()> () at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227
#9  test::__rust_begin_short_backtrace<fn()> () at library/test/src/lib.rs:585
#10 0x00005555555ce074 in alloc::boxed::{impl#44}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global> ()
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694
#11 core::panic::unwind_safe::{impl#23}::call_once<(), alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>> ()
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panic/unwind_safe.rs:271
#12 std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>>, ()> () at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406
#13 std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>>> ()
    at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370
#14 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=()> + core::marker::Send), alloc::alloc::Global>>, ()>
    () at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133
#15 test::run_test_in_process () at library/test/src/lib.rs:608
#16 test::run_test::run_test_inner::{closure#0} () at library/test/src/lib.rs:500
#17 0x00005555555cd3f5 in test::run_test::run_test_inner () at library/test/src/lib.rs:538
#18 0x00005555555cbdc9 in test::run_test () at library/test/src/lib.rs:572
#19 0x00005555555c6752 in test::run_tests<test::console::run_tests_console::{closure#2}> () at library/test/src/lib.rs:313
#20 0x00005555555aeb98 in test::console::run_tests_console () at library/test/src/console.rs:290
#21 0x00005555555c43e5 in test::test_main () at library/test/src/lib.rs:124
#22 0x00005555555c54f1 in test::test_main_static () at library/test/src/lib.rs:143
#23 0x00005555555805e3 in nix::main () at src/lib.rs:1
```

</details>

<details><summary><code>strace nix-09e2df43abb053c6 --test-threads 1  >/dev/null</code></summary>

```dtrace
execve("/home/jtracey/Documents/nix/target/debug/deps/nix-09e2df43abb053c6", ["/home/jtracey/Documents/nix/tar"..., "--test-threads", "1"], 0x7ffe9199c390 /* 47 vars */) = 0
brk(NULL)                               = 0x55571e8ef000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffd4b53c170) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=116461, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 116461, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f24a21af000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3405\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=100888, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f24a21ad000
mmap(NULL, 103496, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f24a2193000
mmap(0x7f24a2196000, 73728, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f24a2196000
mmap(0x7f24a21a8000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f24a21a8000
mmap(0x7f24a21ab000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f24a21ab000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200\363\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=928264, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 930048, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f24a20af000
mprotect(0x7f24a20be000, 864256, PROT_NONE) = 0
mmap(0x7f24a20be000, 499712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xf000) = 0x7f24a20be000
mmap(0x7f24a2138000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x89000) = 0x7f24a2138000
mmap(0x7f24a2191000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe1000) = 0x7f24a2191000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\342\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\270\3{b`\206SF\200#!\335\"V\270\255"..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2215936, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260144, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f24a1e87000
mprotect(0x7f24a1eb3000, 2002944, PROT_NONE) = 0
mmap(0x7f24a1eb3000, 1654784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2c000) = 0x7f24a1eb3000
mmap(0x7f24a2047000, 344064, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7f24a2047000
mmap(0x7f24a209c000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7f24a209c000
mmap(0x7f24a20a2000, 52400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f24a20a2000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f24a1e84000
arch_prctl(ARCH_SET_FS, 0x7f24a1e847c0) = 0
set_tid_address(0x7f24a1e84a90)         = 2429568
set_robust_list(0x7f24a1e84aa0, 24)     = 0
mprotect(0x7f24a209c000, 12288, PROT_READ) = 0
mprotect(0x7f24a2191000, 4096, PROT_READ) = 0
mprotect(0x7f24a21ab000, 4096, PROT_READ) = 0
mprotect(0x55571e825000, 57344, PROT_READ) = 0
mprotect(0x7f24a21ff000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f24a21af000, 116461)          = 0
poll([{fd=0, events=0}, {fd=1, events=0}, {fd=2, events=0}], 3, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f24a1ecd520}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSEGV, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x55571e7d1b70, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x7f24a1ecd520}, NULL, 8) = 0
rt_sigaction(SIGBUS, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x55571e7d1b70, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x7f24a1ecd520}, NULL, 8) = 0
sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f24a21c9000
mprotect(0x7f24a21c9000, 4096, PROT_NONE) = 0
sigaltstack({ss_sp=0x7f24a21ca000, ss_flags=0, ss_size=8192}, NULL) = 0
getrandom("\x21\x90\xaa\x3b\xc4\x92\xdd\x95", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x55571e8ef000
brk(0x55571e910000)                     = 0x55571e910000
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY|O_CLOEXEC) = 3
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "55571e72c000-55571e741000 r--p 0"..., 1024) = 1024
read(3, "/x86_64-linux-gnu/libc.so.6\n7f24"..., 1024) = 1024
read(3, "sr/lib/x86_64-linux-gnu/libm.so."..., 1024) = 1024
read(3, "5911                    /usr/lib"..., 1024) = 756
close(3)                                = 0
sched_getaffinity(2429568, 32, [0, 1, 2, 3]) = 8
statx(0, NULL, AT_STATX_SYNC_AS_STAT, STATX_ALL, NULL) = -1 EFAULT (Bad address)
statx(AT_FDCWD, "/home/jtracey/.terminfo", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffd4b53b480) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/terminfo", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/etc/terminfo/x/xterm-256color", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffd4b53b480) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/terminfo/78/xterm-256color", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffd4b53b480) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/lib/terminfo", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/lib/terminfo/x/xterm-256color", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=3790, ...}) = 0
openat(AT_FDCWD, "/lib/terminfo/x/xterm-256color", O_RDONLY|O_CLOEXEC) = 3
read(3, "\36\2%\0&\0\17\0\235\1\34\6xterm-256color|xterm"..., 8192) = 3790
getrandom("\xcc\xbb\xfe\xd8\xd0\xb0\x2d\x6a\xe6\xdb\x94\x7b\x55\x85\x05\x33", 16, GRND_NONBLOCK) = 16
close(3)                                = 0
ioctl(1, TCGETS, 0x7ffd4b53b990)        = -1 ENOTTY (Inappropriate ioctl for device)
write(1, "\nrunning 48 tests\n", 18)    = 18
write(1, "test features::os::test_parsing_"..., 51) = 51

[SNIP]

close(3)                                = 0
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::aio::t::liocb_is_unpin"..., 37) = 37
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::fdset_c"..., 41) = 41
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::fdset_f"..., 39) = 39
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::fdset_h"..., 43) = 43
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::fdset_i"..., 42) = 42
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::fdset_r"..., 42) = 42
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::test_se"..., 41) = 41
pipe([3, 4])                            = 0
write(4, "hi!", 3)                      = 3
pipe([5, 6])                            = 0
pselect6(6, [3 5], NULL, NULL, {tv_sec=10, tv_nsec=0}, NULL) = 1 (in [3], left {tv_sec=9, tv_nsec=999997898})
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::test_se"..., 46) = 46
pipe([7, 8])                            = 0
write(8, "hi!", 3)                      = 3
pipe([9, 10])                           = 0
pselect6(10, [7 9], NULL, NULL, {tv_sec=10, tv_nsec=0}, NULL) = 1 (in [7], left {tv_sec=9, tv_nsec=999998442})
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::select::tests::test_se"..., 47) = 47
pipe([11, 12])                          = 0
write(12, "hi!", 3)                     = 3
pipe([13, 14])                          = 0
pselect6(14, [11 13], NULL, NULL, {tv_sec=10, tv_nsec=0}, NULL) = 1 (in [11], left {tv_sec=9, tv_nsec=999998542})
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_cl"..., 40) = 40
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_co"..., 43) = 43
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_ex"..., 41) = 41
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_fr"..., 57) = 57
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_fr"..., 55) = 55
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_si"..., 44) = 44
rt_sigaction(SIGRT_1, {sa_handler=0x7f24a1f1c700, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f24a1ecd520}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
mmap(NULL, 2101248, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f24a1c83000
mprotect(0x7f24a1c84000, 2097152, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7f24a1e82e70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2429569], tls=0x7f24a1e83640, child_tidptr=0x7f24a1e83910) = 2429569
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7f24a1e83910, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 2429569, NULL, FUTEX_BITSET_MATCH_ANY) = 0
write(1, "ok", 2)                       = 2
write(1, "\n", 1)                       = 1
write(1, "test sys::signal::tests::test_si"..., 42) = 42
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7f24a1e82e70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[2429570], tls=0x7f24a1e83640, child_tidptr=0x7f24a1e83910) = 2429570
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7f24a1e83910, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 2429570, NULL, FUTEX_BITSET_MATCH_ANY) = ?
+++ killed by SIGUSR1 +++
User defined signal 1
```

</details>

You're right, it does appear to be happening in the test itself in these logs.

**Comment by rtzoeller** [comment]
@jtracey does this reproduce on Ubuntu 22.04? If so I can try to take a look soon.

**Comment by jtracey** [comment]
I'm not seeing it now, no. I'm not sure if that's from the upgrade to 22.04, a change in the code, or some other environment change.

**Comment by rtzoeller** [comment]
@jtracey thanks for checking. I'm going to close this as it doesn't reproduce on the latest Fedora or Ubuntu releases; we can reopen it if it starts manifesting again.
