### ISSUE TITLE
Debug the `test_signal::test_sigsuspend()` test failure in macOS CI

### ISSUE THREAD

**Issue by SteveLauC** [nix-rust/nix#2336]
CI log: https://github.com/nix-rust/nix/actions/runs/8306056722/job/22733675051

```
failures:

---- sys::test_signal::test_sigsuspend stdout ----
thread '<unnamed>' panicked at 'assertion failed: SIGNAL_RECIEVED.load(Ordering::SeqCst)', test/sys/test_signal.rs:386:9
thread 'sys::test_signal::test_sigsuspend' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', test/sys/test_signal.rs:393:6


failures:
    sys::test_signal::test_sigsuspend
```

I can probably do this when I receive my macOS machine.

**Comment by SteveLauC** [comment]
I cannot reproduce this on my m1 mac:

```sh
$ uname -a
Darwin Steves-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
```

Have no idea why that bool value has not been updated (by the signal handler) to `true` when `sigsuspend()` returns. On Linux, it is explicitly stated that when `sigsuspend()` returns, the signal handler is guaranteed to be executed:

> If the signal is caught, then `sigsuspend()` returns after the signal handler returns

The macOS [manual](https://keith.github.io/xcode-man-pages/sigsuspend.2.html) does not mention this.

**Comment by TheJonny** [comment]
maybe #2375 fixes it, but without a reliable way to reproduce it, its hard to tell

**Comment by xtqqczze** [comment]
Occurred again in https://github.com/nix-rust/nix/actions/runs/23904714892/job/69710307136?pr=2762
