### ISSUE TITLE
TRUST CI: x86_64-unknown-linux-musl SIGSEGV

### ISSUE THREAD

**Issue by posborne** [nix-rust/nix#530]
```
running 61 tests
error: process didn't exit successfully: `/target/x86_64-unknown-linux-musl/debug/deps/test-3fdc771e27202ed2` (signal: 11, SIGSEGV: invalid memory reference)
```

https://travis-ci.org/berkowski/nix/jobs/205534672

**Comment by posborne** [comment]
Reproduced locally... Here's the backtrace.  Seems to be in `__aio_get_queue()`.  A lot of stuff optimized out, but it's something to start with.  For linux a lot of the AIO functionality is implemented in libc, so this is quite likely some different (and possibly a bug compared with) glibc.

```
(gdb) bt
#0  0x00000000004e30ea in je_extent_tree_szad_remove (rbtree=rbtree@entry=0x758d48 <base_avail_szad>, node=node@entry=0x7ffff7c00000)
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/extent.c:40
#1  0x00000000004d7ca6 in je_base_alloc (size=<optimized out>)
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/base.c:98
#2  0x00000000004d69f4 in je_arena_new (ind=2) at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/arena.c:3329
#3  0x00000000004cb75f in arena_init_locked (ind=<optimized out>)
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:437
#4  0x00000000004cbcb9 in je_arena_choose_hard (tsd=tsd@entry=0x7ffff7ff5a60)
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:610
#5  0x00000000004eb818 in je_arena_choose (arena=0x0, tsd=0x7ffff7ff5a60) at include/jemalloc/internal/jemalloc_internal.h:791
#6  je_tcache_get_hard (tsd=tsd@entry=0x7ffff7ff5a60) at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/tcache.c:307
#7  0x00000000004ccaa0 in je_tcache_get (create=true, tsd=<optimized out>)
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/tcache.h:236
#8  je_icalloc (ind=20, size=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:969
#9  calloc (num=<optimized out>, size=<optimized out>) at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc_jemalloc/../jemalloc/src/jemalloc.c:1737
#10 0x00000000004ed5f2 in __aio_get_queue ()
#11 0x0000000000000000 in ?? ()
```

**Comment by Susurrus** [comment]
All supported platforms are running safely in CI, so I think this issue can be closed.
